# Generated by Django 6.0.2 on 2026-03-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_trending",
            field=models.BooleanField(default=False),
        ),
    ]
