# Generated by Django 6.0.2 on 2026-03-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_is_trending"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
