# Generated by Django 6.0.2 on 2026-03-10 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_news_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="likes",
        ),
        migrations.AddField(
            model_name="news",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_news", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
