# Generated by Django 6.0.2 on 2026-03-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
