# Generated by Django 6.0.2 on 2026-03-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="breaking",
            field=models.BooleanField(default=False),
        ),
    ]
