# Generated by Django 6.0.1 on 2026-03-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_bio_user_linkedin_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
